# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Emmanuel Bernard
subtitle: "Builds Open Source Software"
email:
description: >- # this means to ignore newlines until "baseurl:"
  Emmanuel Bernard is an Open Source software engineer.
  Java Champion, he is best known for his lead of Hibernate and Quarkus.
twitter_username: emmanuelbernard
github_username: emmanuelbernard
#a minimum size of 120px by 120px, and less than 1MB in file size
og_image: /images/headshot/emmanuel-headshot-square-1200px.jpg

minimal_mistakes_skin    : "mint" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
search: true

url: https://emmanuelbernard.com
#feed
# URL used by pages
atom_feed:
  path: /blog/feed.atom
# config to generate feed with jekyll-feed
feed:
  path: /blog/feed.atom
  posts_limit: 200

# Removing Google Analytics due to GDPR and CNIL
# #Analyzers
# analytics:
#   provider: "google-gtag" #"google" # false (default), "google", "google-universal", "google-gtag", "custom"
#   google:
#     tracking_id          : "UA-3479508-6"
#     anonymize_ip         : false # true, false (default

#Comments
comments:
  provider: "disqus"
  disqus:
    shortname: "emmanuelbernard-com"


# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "<!--more-->"
incremental: false
#remote_theme: mmistakes/minimal-mistakes
# Outputting
paginate: 5 # amount of posts to show
paginate_path: /blog/page/:num/
timezone: Europe/Paris # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
  - .htaccess

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"
  - TODO
  - readme.md
  - .rvmrc


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Emmanuel Bernard"
  # avatar : "/images/headshot/201310EmmanuelBernardSquare.jpg"
  avatar : "/images/headshot/emmanuel-headshot-square-1200px.jpg"
  bio    : "Emmanuel Bernard is an Open Source software engineer. Java Champion, he is best known for his lead of Hibernate and Quarkus."
  links:
    - label: "Bio"
      icon: "fas fa-fw fa-link"
      url: "https://emmanuelbernard.com/bio/"
    - label: "Bluesky"
      icon: "fab fa-fw fa-bluesky"
      url: "https://bsky.app/profile/emmanuelbernard.com"
    - label: "X/Twitter"
      icon: "fab fa-fw fa-x-twitter"
      url: "https://twitter.com/emmanuelbernard"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/emmanuelbernard"
    - label: "Email"
      icon: "fas fa-fw fa-at"
      url: "mailto:contact@mel.emmanuelbernard.com"

social:
  type: Person
  name:  "Emmanuel Bernard"
  links:
    - "https://twitter.com/emmanuelbernard"
    - "https://www.linkedin.com/in/emmanuelbernard"

footer:
  links:
    - label: "Bluesky"
      icon: "fab fa-fw fa-bluesky"
      url: "https://bsky.app/profile/emmanuelbernard.com"
    - label: "X/Twitter"
      icon: "fab fa-fw fa-x-twitter"
      url: "https://twitter.com/emmanuelbernard"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/emmanuelbernard"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      permalink: /blog/:year/:month/:day/:title/
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
  - scope:
      path: "presentations/inverted-index/reveal.js/"
    values:
      sitemap: false

category_archive:
  type: liquid
  path: /blog/categories/
tag_archive:
  type: liquid
  path: /blog/tags/
