#!/bin/sh

set -e

bundle install
bundle exec jekyll clean
JEKYLL_ENV=production bundle exec jekyll build

while [[ $# -gt 0 ]]
do
  param="$1"
  case $param in
    -p|--publish)
    # publish the website
    shift # shift to next argument
    chmod -R go+r _site/
    rsync -avz --delete --filter="- publish.sh" --filter="- Gemfile" --filter="- Gemfile.lock" _site/ lcc-web:/var/www/emmanuelbernard
    ;;
  esac
done
exit 0;
