#!/bin/sh

if [ ! -z "$1" -a "$1" = '--prod' ]; then
  export JEKYLL_ENV="production"
fi

bundle install
bundle exec jekyll clean
# future has a bug that removes drafts
#bundle exec jekyll serve --drafts --livereload --future
bundle exec jekyll serve --drafts --livereload 
